---
# AirGradient DIY Basic
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-basic"
  friendly_name: "AG Basic"
  name_add_mac_suffix: "false"  # Must have quotes around value
  sensor_update_interval: 60s

# Enable Home Assistant API
api:
  encryption:
    key:  # Add encryption key as desired

ota:
  - platform: esphome
    password: !secret ota_password

packages:
  board: github://Gzu/airgradient_esphome/packages/airgradient_d1_mini_board.yaml
  captive_portal: github://Gzu/airgradient_esphome/packages/captive_portal.yaml
  pm_2.5: github://Gzu/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://Gzu/airgradient_esphome/packages/sensor_s8.yaml
  # temp_humidity: github://Gzu/airgradient_esphome/packages/sensor_sht40.yaml
  temp_humidity: github://Gzu/airgradient_esphome/packages/sensor_sht30.yaml
  voc_nox: github://Gzu/airgradient_esphome/packages/sensor_sgp41.yaml
  aqi_leds: github://Gzu/airgradient_esphome/packages/aqi_leds.yaml
  display: github://Gzu/airgradient_esphome/packages/display_ssd1306.yaml
  wifi: github://Gzu/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://Gzu/airgradient_esphome/packages/sensor_uptime.yaml
