sensor:
  - platform: uptime
    name: "Uptime"
    id: device_uptime
    disabled_by_default: false
    force_update: false
    unit_of_measurement: s
    icon: mdi:timer-outline
    accuracy_decimals: 0
    device_class: duration
    state_class: total_increasing
    entity_category: diagnostic
    update_interval: ${sensor_update_interval}
    type: seconds
    
